using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class movimientoArmaAlien : MonoBehaviour
{
    public Transform targetTransform; // Objeto cuya posici贸n y rotaci贸n queremos igualar

    void Update()
    {
        if (targetTransform != null)
        {
            // Iguala la posici贸n y rotaci贸n del objeto actual con el objeto de destino
            transform.position = targetTransform.position;
            transform.rotation = targetTransform.rotation;
        }
        else
        {
            Debug.LogError("Objeto de destino no asignado en el script MatchTransform.");
        }
    }
}
